---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-custom-container
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: pushpendrasingh3tcscom/demo-app:2.0.6
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-apache
  namespace: demo
  labels:
    app: apache
spec:
  type: NodePort      
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
