---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-container
  namespace: demo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: pushpendrasingh3tcscom/demo-app:2.0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-apache
  namespace: demo-app
  labels:
    app: apache
spec:
  type: NodePort      
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
