---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-demo-application
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-project
  source:
    repoURL: https://github.com/pushpendrasingh3/ActionsDemo.git
    targetRevision: main
    #targetRevision: HEAD
    path: argocd-cicd-setup/prod
  destination:
    server: https://34.47.151.239
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
      
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
