name: CI + CD

on:
  push:
    branches: [ feature ]
    paths-ignore:
      - '.github/workflows/*'  
  workflow_dispatch:
    branches: [ feature, release, main ]
    paths-ignore:
      - '.github/workflows/*'  
  pull_request:
    branches: [ release, main ]
    types: [closed]  
          
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo "Hello, world!"
        #- name: Output event data    
        #run: echo "${{ toJSON(github.event) }}"
      - name: Block close  
        run: echo "---------------------------"
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event.ref == 'refs/heads/feature'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying in Development! 

    
  DeployStaging:
    name: Deploy to Staging 
    if: (( github.event.ref != 'refs/heads/feature' ) && ( ${{ github.event.pull_request.merged }} ))
       echo "(( github.event.ref != 'refs/heads/feature' ) && ( ${{ github.event.pull_request.merged }} ))"  
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying in Staging! 
           

  DeployProd:
    name: Deploy to Production 
    #if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
    #if: github.event.ref == 'refs/heads/main'  
    needs: [DeployStaging]
      #needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying in Production!  
